servers:
    - "Creative"
    - "Skywars"
    - "Factions"
    - "Prisons1"
    - "Prisons2"
    - "Skyblock"
    - "Yellow1"
    - "Yellow2"
    - "Red"
    - "Ancient"
    - "Iceage"
    - "Hub1"
    - "Hub2"
    - "Lobby"
